export interface RadioStation {
  id: string;
  name: string;
  country: string;
  city: string;
  genre: string;
  streamUrl: string;
  color: string;
  icon: string;
  tagline: string;
  favorite: boolean;
  verified: boolean;
}

export const RADIO_GENRES = [
  "All",
  "Pop / Hits",
  "Urban / R&B",
  "Hip Hop",
  "News / Talk",
  "Vernacular",
  "Indie / Trending",
] as const;

export const RADIO_COUNTRIES = ["All", "Kenya", "Uganda", "Tanzania", "Rwanda"] as const;

// All streams verified reachable over HTTPS (checked 2026-09). Streams pointing
// at Icecast/Shoutcast servers also expose realtime now-playing metadata, which
// /api/radio/status resolves.
export const STATIONS: RadioStation[] = [
  {
    id: "capital-fm",
    name: "Capital FM 98.4",
    country: "Kenya",
    city: "Nairobi",
    genre: "Pop / Hits",
    streamUrl: "https://atunwadigital.streamguys1.com/capitalfm",
    color: "#ef4444",
    icon: "C",
    tagline: "Kenya's #1 hit music station",
    favorite: true,
    verified: true,
  },
  {
    id: "nrg-radio",
    name: "NRG Radio",
    country: "Kenya",
    city: "Nairobi",
    genre: "Indie / Trending",
    streamUrl: "https://streamingv2.shoutcast.com/nrg-radio-ke",
    color: "#a855f7",
    icon: "N",
    tagline: "The future sound of Kenya",
    favorite: true,
    verified: true,
  },
  {
    id: "radio-47",
    name: "Radio 47",
    country: "Kenya",
    city: "Nairobi",
    genre: "Pop / Hits",
    streamUrl: "https://streaming.shoutcast.com/radio-47",
    color: "#f59e0b",
    icon: "47",
    tagline: "Songs for every mood",
    favorite: false,
    verified: true,
  },
  {
    id: "kameme-fm",
    name: "Kameme FM",
    country: "Kenya",
    city: "Nairobi",
    genre: "Vernacular",
    streamUrl: "https://kamemefm-atunwadigital.streamguys1.com/kamemefm",
    color: "#22c55e",
    icon: "K",
    tagline: "Kikuyu hits, news and talk",
    favorite: false,
    verified: true,
  },
  {
    id: "nation-fm",
    name: "Nation FM",
    country: "Kenya",
    city: "Nairobi",
    genre: "News / Talk",
    streamUrl: "https://stream.radiojar.com/3by7s8eg65quv",
    color: "#3b82f6",
    icon: "NF",
    tagline: "Kenya's current affairs voice",
    favorite: false,
    verified: true,
  },
  {
    id: "ghetto-radio",
    name: "Ghetto Radio",
    country: "Kenya",
    city: "Nairobi",
    genre: "Hip Hop",
    streamUrl: "https://stream.zeno.fm/cs4q33arb2zuv",
    color: "#ec4899",
    icon: "G",
    tagline: "Sheng hip hop from the streets",
    favorite: false,
    verified: true,
  },
  {
    id: "kenya1-fm",
    name: "KENYA1 FM",
    country: "Kenya",
    city: "Nairobi",
    genre: "Pop / Hits",
    streamUrl: "https://stream.zeno.fm/cmgkmed5u18uv",
    color: "#14b8a6",
    icon: "1",
    tagline: "Non-stop Kenyan hits",
    favorite: false,
    verified: true,
  },
  {
    id: "radio-safari",
    name: "Radio Safari",
    country: "Kenya",
    city: "Nairobi",
    genre: "Vernacular",
    streamUrl: "https://stream.zeno.fm/t65cszbgunhvv",
    color: "#f97316",
    icon: "S",
    tagline: "Stories and music from the wild",
    favorite: false,
    verified: true,
  },
  {
    id: "galaxie-fm",
    name: "Galaxie FM 95.3",
    country: "Uganda",
    city: "Kampala",
    genre: "Pop / Hits",
    streamUrl: "https://listen.radioking.com/radio/15684/stream/29075",
    color: "#06b6d4",
    icon: "GX",
    tagline: "Kampala's biggest hits",
    favorite: true,
    verified: true,
  },
  {
    id: "nrg-uganda",
    name: "NRG Radio Uganda",
    country: "Uganda",
    city: "Kampala",
    genre: "Indie / Trending",
    streamUrl: "https://dc4.serverse.com/proxy/nrgugstream/stream",
    color: "#8b5cf6",
    icon: "NU",
    tagline: "Uganda's trending sound",
    favorite: false,
    verified: true,
  },
  {
    id: "spice-fm",
    name: "Spice FM 98.8",
    country: "Uganda",
    city: "Kampala",
    genre: "Urban / R&B",
    streamUrl: "https://spice988fm.radioca.st/stream",
    color: "#f43f5e",
    icon: "SP",
    tagline: "Kampala's urban pulse",
    favorite: false,
    verified: true,
  },
  {
    id: "next-radio",
    name: "Next Radio 106.1",
    country: "Uganda",
    city: "Kampala",
    genre: "Pop / Hits",
    streamUrl: "https://stream-154.zeno.fm/lbca7zintcnuv",
    color: "#eab308",
    icon: "NR",
    tagline: "The next big thing",
    favorite: false,
    verified: true,
  },
  {
    id: "ear-radio",
    name: "East Africa Radio",
    country: "Tanzania",
    city: "Dar es Salaam",
    genre: "Urban / R&B",
    streamUrl: "https://eatv.radioca.st/stream",
    color: "#10b981",
    icon: "EA",
    tagline: "Bongo flava and East African vibes",
    favorite: true,
    verified: true,
  },
  {
    id: "capital-tz",
    name: "Capital Radio",
    country: "Tanzania",
    city: "Dar es Salaam",
    genre: "Pop / Hits",
    streamUrl: "https://capitalradio.radioca.st/stream",
    color: "#0ea5e9",
    icon: "CT",
    tagline: "Tanzania's hit station",
    favorite: false,
    verified: true,
  },
  {
    id: "crown-fm",
    name: "Crown FM",
    country: "Tanzania",
    city: "Arusha",
    genre: "Vernacular",
    streamUrl: "https://radio.crownmedia.co.tz:8443/crown",
    color: "#84cc16",
    icon: "CR",
    tagline: "Northern Tanzania's voice",
    favorite: false,
    verified: true,
  },
  {
    id: "radio-rwanda",
    name: "Radio Rwanda",
    country: "Rwanda",
    city: "Kigali",
    genre: "News / Talk",
    streamUrl: "https://listen.rba.co.rw:8008/rwanda",
    color: "#2563eb",
    icon: "RR",
    tagline: "The national broadcaster",
    favorite: false,
    verified: true,
  },
  {
    id: "menya-fm",
    name: "MENYA FM",
    country: "Rwanda",
    city: "Kigali",
    genre: "Pop / Hits",
    streamUrl: "https://stream.zeno.fm/k5rq7qwkggauv",
    color: "#db2777",
    icon: "M",
    tagline: "Kinyarwanda hits and talk",
    favorite: false,
    verified: true,
  },
];

export function getStationById(id: string | null): RadioStation | null {
  if (!id) return null;
  return STATIONS.find((s) => s.id === id) ?? null;
}