export interface RadioStation {
  id: string;
  name: string;
  country: string;
  city: string;
  region: string;
  genre: string;
  language: string;
  frequency: string;
  streamUrl: string;
  color: string;
  icon: string;
  tagline: string;
  logoUrl?: string;
  programming: string[];
  favorite: boolean;
  verified: boolean;
}

export const RADIO_GENRES = [
  "All",
  "Pop / Hits",
  "Urban / R&B",
  "Hip Hop",
  "News / Talk",
  "Vernacular",
  "Indie / Trending",
  "Gospel",
  "Bongo Flava",
  "Afrobeats",
] as const;

export const RADIO_COUNTRIES = [
  "All",
  "Kenya",
  "Uganda",
  "Tanzania",
  "Rwanda",
  "Nigeria",
  "South Africa",
  "Ghana",
  "International",
] as const;

export const STATION_REGIONS = [
  "All",
  "Nairobi",
  "Coast",
  "Rift Valley",
  "Kampala",
  "Dar es Salaam",
  "Arusha",
  "Kigali",
  "Lagos",
  "Johannesburg",
  "Accra",
  "London",
] as const;

export const STATIONS: RadioStation[] = [
  /* ============================== KENYA ============================== */
  {
    id: "capital-fm",
    name: "Capital FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Pop / Hits",
    language: "English",
    frequency: "98.4 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/capitalfm",
    color: "#ef4444",
    icon: "C",
    tagline: "Kenya's #1 hit music station",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Capital_Fm_Logo.svg/200px-Capital_Fm_Logo.svg.png",
    programming: ["Morning Drive", "Hits", "News Bulletins", "Talk"],
    favorite: true,
    verified: true,
  },
  {
    id: "nrg-radio",
    name: "NRG Radio",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Indie / Trending",
    language: "English / Sheng",
    frequency: "90.9 FM",
    streamUrl: "https://stream.zeno.fm/cmgkmed5u18uv",
    color: "#a855f7",
    icon: "N",
    tagline: "The future sound of Kenya",
    programming: ["NRG Breakfast", "New Music", "Gen-Z Talk"],
    favorite: true,
    verified: true,
  },
  {
    id: "radio-47",
    name: "Radio 47",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Pop / Hits",
    language: "English / Swahili",
    frequency: "47 FM",
    streamUrl: "https://stream.zeno.fm/t65cszbgunhvv",
    color: "#f59e0b",
    icon: "47",
    tagline: "Songs for every mood",
    programming: ["Classic Mix", "Workday Hits", "Weekend Party"],
    favorite: false,
    verified: true,
  },
  {
    id: "classic-105",
    name: "Classic 105",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Pop / Hits",
    language: "English",
    frequency: "105.3 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/classic105",
    color: "#dc2626",
    icon: "105",
    tagline: "Timeless hits from the 80s to today",
    programming: ["Classic Drive", "Greatest Hits", "Workday Anthems"],
    favorite: false,
    verified: true,
  },
  {
    id: "kiss-100",
    name: "Kiss 100",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Urban / R&B",
    language: "English / Sheng",
    frequency: "100.0 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/kiss100fm",
    color: "#f43f5e",
    icon: "K",
    tagline: "Kenya's non-stop urban music",
    programming: ["Kiss Drive", "Urban Hits", "R&B Nights"],
    favorite: false,
    verified: true,
  },
  {
    id: "hot-96",
    name: "Hot 96",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Hip Hop",
    language: "English / Sheng",
    frequency: "96.0 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/hot96",
    color: "#f97316",
    icon: "96",
    tagline: "Hip hop and urban hits all day",
    programming: ["Hot Breakfast", "Hip Hop Flow", "Night Beats"],
    favorite: false,
    verified: true,
  },
  {
    id: "milele-fm",
    name: "Milele FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Vernacular",
    language: "Swahili",
    frequency: "95.1 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/milelefm",
    color: "#eab308",
    icon: "M",
    tagline: "Swahili hits, stories and talk",
    programming: ["Bongo Mix", "Swahili Talk", "Request Hour"],
    favorite: false,
    verified: true,
  },
  {
    id: "radio-maisha",
    name: "Radio Maisha",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Vernacular",
    language: "Swahili",
    frequency: "97.1 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/radiomaisha",
    color: "#14b8a6",
    icon: "RM",
    tagline: "Swahili music and news from the Nation family",
    programming: ["Maisha Drive", "Swahili News", "Bongo Flava"],
    favorite: false,
    verified: true,
  },
  {
    id: "inooro-fm",
    name: "Inooro FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Vernacular",
    language: "Kikuyu",
    frequency: "98.5 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/inoorofm",
    color: "#16a34a",
    icon: "I",
    tagline: "Kikuyu hits, news and talk",
    programming: ["Kikuyu Mix", "Morning Talk", "Farming Show"],
    favorite: false,
    verified: true,
  },
  {
    id: "nation-fm",
    name: "Nation FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "News / Talk",
    language: "English",
    frequency: "93.3 FM",
    streamUrl: "https://stream.zeno.fm/9wfmjkmsk8urv",
    color: "#3b82f6",
    icon: "NF",
    tagline: "Kenya's current affairs voice",
    programming: ["Morning Briefing", "Politics Today", "Business Hour"],
    favorite: false,
    verified: true,
  },
  {
    id: "ghetto-radio",
    name: "Ghetto Radio",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Hip Hop",
    language: "Sheng",
    frequency: "89.5 FM",
    streamUrl: "https://stream.zeno.fm/cs4q33arb2zuv",
    color: "#ec4899",
    icon: "G",
    tagline: "Sheng hip hop from the streets",
    programming: ["Sheng Flow", "Underground Cyphers", "Gengetone Mix"],
    favorite: false,
    verified: true,
  },
  {
    id: "kameme-fm",
    name: "Kameme FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Vernacular",
    language: "Kikuyu",
    frequency: "101.1 FM",
    streamUrl: "https://stream.zeno.fm/0pe6jk6mzg8uv",
    color: "#22c55e",
    icon: "K",
    tagline: "Kikuyu hits, news and talk",
    programming: ["Kikuyu Classics", "Community Talk"],
    favorite: false,
    verified: true,
  },

  /* ============================== UGANDA ============================== */
  {
    id: "galaxie-fm",
    name: "Galaxie FM",
    country: "Uganda",
    city: "Kampala",
    region: "Kampala",
    genre: "Pop / Hits",
    language: "English / Luganda",
    frequency: "95.3 FM",
    streamUrl: "https://listen.radioking.com/radio/15684/stream/29075",
    color: "#06b6d4",
    icon: "GX",
    tagline: "Kampala's biggest hits",
    programming: ["Breakfast Drive", "Luganda Hits", "Sunday Mix"],
    favorite: true,
    verified: true,
  },
  {
    id: "nrg-uganda",
    name: "NRG Radio Uganda",
    country: "Uganda",
    city: "Kampala",
    region: "Kampala",
    genre: "Indie / Trending",
    language: "English",
    frequency: "91.3 FM",
    streamUrl: "https://stream.zeno.fm/lbca7zintcnuv",
    color: "#8b5cf6",
    icon: "NU",
    tagline: "Uganda's trending sound",
    programming: ["NRG Drive", "Trending Now"],
    favorite: false,
    verified: true,
  },
  {
    id: "spice-fm",
    name: "Spice FM",
    country: "Uganda",
    city: "Kampala",
    region: "Kampala",
    genre: "Urban / R&B",
    language: "English / Luganda",
    frequency: "98.8 FM",
    streamUrl: "https://spice988fm.radioca.st/stream",
    color: "#f43f5e",
    icon: "SP",
    tagline: "Kampala's urban pulse",
    programming: ["Urban Breakfast", "R&B Evenings", "Luganda Mix"],
    favorite: false,
    verified: true,
  },
  {
    id: "next-radio",
    name: "Next Radio",
    country: "Uganda",
    city: "Kampala",
    region: "Kampala",
    genre: "Pop / Hits",
    language: "English / Luganda",
    frequency: "106.1 FM",
    streamUrl: "https://stream-154.zeno.fm/lbca7zintcnuv",
    color: "#eab308",
    icon: "NR",
    tagline: "The next big thing",
    programming: ["New Music First", "Kampala Nights"],
    favorite: false,
    verified: true,
  },
  {
    id: "sanyu-fm",
    name: "Sanyu FM",
    country: "Uganda",
    city: "Kampala",
    region: "Kampala",
    genre: "Pop / Hits",
    language: "English / Luganda",
    frequency: "88.2 FM",
    streamUrl: "https://stream.zeno.fm/a4pcrm3m5quv",
    color: "#f97316",
    icon: "S",
    tagline: "Uganda's oldest private station",
    programming: ["Morning Breeze", "Luganda Hits", "Classic Show"],
    favorite: false,
    verified: true,
  },

  /* ============================= TANZANIA ============================= */
  {
    id: "ear-radio",
    name: "East Africa Radio",
    country: "Tanzania",
    city: "Dar es Salaam",
    region: "Dar es Salaam",
    genre: "Urban / R&B",
    language: "Swahili / English",
    frequency: "Digital",
    streamUrl: "https://eatv.radioca.st/stream",
    color: "#10b981",
    icon: "EA",
    tagline: "Bongo flava and East African vibes",
    programming: ["Bongo Flava Mix", "East African Hits", "Request Show"],
    favorite: true,
    verified: true,
  },
  {
    id: "capital-tz",
    name: "Capital Radio",
    country: "Tanzania",
    city: "Dar es Salaam",
    region: "Dar es Salaam",
    genre: "Pop / Hits",
    language: "Swahili / English",
    frequency: "94.1 FM",
    streamUrl: "https://capitalradio.radioca.st/stream",
    color: "#0ea5e9",
    icon: "CT",
    tagline: "Tanzania's hit station",
    programming: ["Capital Drive", "Bongo Hits", "Weekend Mix"],
    favorite: false,
    verified: true,
  },
  {
    id: "crown-fm",
    name: "Crown FM",
    country: "Tanzania",
    city: "Arusha",
    region: "Arusha",
    genre: "Vernacular",
    language: "Swahili",
    frequency: "103.4 FM",
    streamUrl: "https://stream.zeno.fm/b3euphqjkzguv",
    color: "#84cc16",
    icon: "CR",
    tagline: "Northern Tanzania's voice",
    programming: ["Arusha Morning", "Swahili Classics", "Maasai Stories"],
    favorite: false,
    verified: true,
  },
  {
    id: "clouds-fm",
    name: "Clouds FM",
    country: "Tanzania",
    city: "Dar es Salaam",
    region: "Dar es Salaam",
    genre: "Bongo Flava",
    language: "Swahili",
    frequency: "102.5 FM",
    streamUrl: "https://stream.zeno.fm/fha6wsbmbg8uv",
    color: "#8b5cf6",
    icon: "CF",
    tagline: "Tanzania's #1 Bongo Flava station",
    programming: ["Clouds Breakfast", "Bongo Hot", "Mic Tamtam"],
    favorite: false,
    verified: true,
  },

  /* ============================== RWANDA ============================== */
  {
    id: "radio-rwanda",
    name: "Radio Rwanda",
    country: "Rwanda",
    city: "Kigali",
    region: "Kigali",
    genre: "News / Talk",
    language: "Kinyarwanda / French",
    frequency: "95.0 FM",
    streamUrl: "https://listen.rba.co.rw:8008/rwanda",
    color: "#2563eb",
    icon: "RR",
    tagline: "The national broadcaster",
    programming: ["Morning News", "Kinyarwanda Talk", "National Service"],
    favorite: false,
    verified: true,
  },
  {
    id: "menya-fm",
    name: "MENYA FM",
    country: "Rwanda",
    city: "Kigali",
    region: "Kigali",
    genre: "Pop / Hits",
    language: "Kinyarwanda",
    frequency: "105.0 FM",
    streamUrl: "https://stream.zeno.fm/k5rq7qwkggauv",
    color: "#db2777",
    icon: "M",
    tagline: "Kinyarwanda hits and talk",
    programming: ["Kinyarwanda Hits", "Youth Talk", "Weekend Party"],
    favorite: false,
    verified: true,
  },

  /* ============================== NIGERIA ============================== */
  {
    id: "beat-fm",
    name: "Beat FM 99.5",
    country: "Nigeria",
    city: "Lagos",
    region: "Lagos",
    genre: "Afrobeats",
    language: "English / Pidgin",
    frequency: "99.5 FM",
    streamUrl: "https://stream.zeno.fm/4lkfjbmamquv",
    color: "#f59e0b",
    icon: "BF",
    tagline: "Nigeria's Afrobeats heartbeat",
    programming: ["Morning Rush", "Afrobeats Mix", "Lagos Nights"],
    favorite: false,
    verified: true,
  },
  {
    id: "cool-fm",
    name: "Cool FM 96.9",
    country: "Nigeria",
    city: "Lagos",
    region: "Lagos",
    genre: "Pop / Hits",
    language: "English / Pidgin",
    frequency: "96.9 FM",
    streamUrl: "https://stream.zeno.fm/ys6xu2dnhluv",
    color: "#06b6d4",
    icon: "CF",
    tagline: "Lagos' hottest hits",
    programming: ["Cool Drive", "Hit Music", "Lagos Vibes"],
    favorite: false,
    verified: true,
  },
  {
    id: "wazobia-fm",
    name: "Wazobia FM 99.5",
    country: "Nigeria",
    city: "Lagos",
    region: "Lagos",
    genre: "Vernacular",
    language: "Yoruba / Pidgin",
    frequency: "99.5 FM",
    streamUrl: "https://stream.zeno.fm/tq7ebbmamquv",
    color: "#16a34a",
    icon: "W",
    tagline: "Lagos in your language",
    programming: ["Yoruba Morning", "Pidgin Show", "Local Hits"],
    favorite: false,
    verified: true,
  },

  /* ============================= SOUTH AFRICA ============================ */
  {
    id: "metro-fm",
    name: "METRO FM",
    country: "South Africa",
    city: "Johannesburg",
    region: "Johannesburg",
    genre: "Urban / R&B",
    language: "English / Zulu",
    frequency: "104.8 FM",
    streamUrl: "https://stream.zeno.fm/u9u4g5u4sruv",
    color: "#dc2626",
    icon: "M",
    tagline: "South Africa's urban beat",
    programming: ["Metro Drive", "Urban Jazz", "House Music"],
    favorite: false,
    verified: true,
  },
  {
    id: "5fm",
    name: "5FM",
    country: "South Africa",
    city: "Johannesburg",
    region: "Johannesburg",
    genre: "Pop / Hits",
    language: "English",
    frequency: "95.0 FM",
    streamUrl: "https://stream.zeno.fm/pf3bcuqsngquv",
    color: "#f97316",
    icon: "5",
    tagline: "South Africa's youth radio",
    programming: ["5 Breakfast", "Top 40", "After Dark"],
    favorite: false,
    verified: true,
  },
  {
    id: "jacaranda-fm",
    name: "Jacaranda FM",
    country: "South Africa",
    city: "Johannesburg",
    region: "Johannesburg",
    genre: "Pop / Hits",
    language: "English / Afrikaans",
    frequency: "94.2 FM",
    streamUrl: "https://stream.zeno.fm/ba2fbrfkwruv",
    color: "#7c3aed",
    icon: "JF",
    tagline: "Great music and more",
    programming: ["Martin Bester", "Top 40", "Weekend Breakfast"],
    favorite: false,
    verified: true,
  },

  /* ================================ GHANA ================================ */
  {
    id: "joy-fm",
    name: "Joy FM",
    country: "Ghana",
    city: "Accra",
    region: "Accra",
    genre: "News / Talk",
    language: "English / Twi",
    frequency: "99.7 FM",
    streamUrl: "https://stream.zeno.fm/7s9ybqk2shquv",
    color: "#2563eb",
    icon: "JF",
    tagline: "Ghana's most trusted news station",
    programming: ["Super Morning Show", "Newsfile", "Prime Take"],
    favorite: false,
    verified: true,
  },
  {
    id: "adom-fm",
    name: "Adom FM",
    country: "Ghana",
    city: "Accra",
    region: "Accra",
    genre: "Vernacular",
    language: "Twi",
    frequency: "106.3 FM",
    streamUrl: "https://stream.zeno.fm/n6g9ufrfkwruv",
    color: "#ef4444",
    icon: "AF",
    tagline: "Ghana's leading Twi station",
    programming: ["Adom Dwaso", "Badwam Tribunal", "Nkommo Womu"],
    favorite: false,
    verified: true,
  },

  /* ============================ INTERNATIONAL =========================== */
  {
    id: "bbc-world",
    name: "BBC World Service",
    country: "International",
    city: "London",
    region: "London",
    genre: "News / Talk",
    language: "English",
    frequency: "Digital",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service",
    color: "#991b1b",
    icon: "BBC",
    tagline: "The world's radio station",
    programming: ["World News", "Africa Daily", "Focus on Africa"],
    favorite: false,
    verified: true,
  },
  {
    id: "france24",
    name: "France 24 English",
    country: "International",
    city: "London",
    region: "London",
    genre: "News / Talk",
    language: "English / French",
    frequency: "Digital",
    streamUrl: "https://stream.zeno.fm/france24en.mp3",
    color: "#2563eb",
    icon: "F24",
    tagline: "International news from Paris",
    programming: ["News Live", "The Debate", "Business Africa"],
    favorite: false,
    verified: true,
  },
  {
    id: "ntv-kenya",
    name: "NTV Kenya",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "News / Talk",
    language: "English / Swahili",
    frequency: "Digital",
    streamUrl: "https://stream.zeno.fm/smgpy6wrgo8uv",
    color: "#06b6d4",
    icon: "NTV",
    tagline: "Kenya's news leader",
    programming: ["NTV Today", "NTV at One", "Weekend Edition"],
    favorite: false,
    verified: true,
  },
  {
    id: "qfm",
    name: "Q FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Urban / R&B",
    language: "English / Sheng",
    frequency: "96.3 FM",
    streamUrl: "https://stream.zeno.fm/tq7ebbmamquv",
    color: "#e879f9",
    icon: "Q",
    tagline: "Nairobi's R&B groove",
    programming: ["R&B Evenings", "Sheng Hour", "Weekend Mix"],
    favorite: false,
    verified: true,
  },
];

export function getStationById(id: string | null): RadioStation | null {
  if (!id) return null;
  return STATIONS.find((s) => s.id === id) ?? null;
}

export function getStationsByCountry(country: string): RadioStation[] {
  return STATIONS.filter((s) => s.country === country);
}
