import type { RadioStation } from "@/lib/radio-stations";

/**
 * The ad-free HD roster: stations that cannot serve you a spot at all.
 *
 * ## Why this exists as its own curation
 *
 * The dial's East African core is a service — you go there for Radio Citizen,
 * not for a bitrate. This list is the opposite: it is chosen for three
 * properties, and a station has to have all three to be here.
 *
 *  1. **Commercial-free by licence or by funding.** Public broadcasters (Radio
 *     France) and listener-supported services (SomaFM, Radio Paradise, NTS,
 *     KEXP). Somebody else already paid for the airtime, so there is no ad
 *     server in the path and nothing to geolocate. This is the property that
 *     matters most: a station that does not sell listener time cannot decide
 *     that a listener in Nairobi should hear a German spot, no matter which IP
 *     the request arrives from.
 *  2. **High bitrate.** Everything here serves at least 128 kbps, and mostly
 *     192–320. That is what makes direct playback worth having — the listener
 *     gets the mount's real quality rather than whatever a serverless function
 *     could forward inside its execution window.
 *  3. **https.** Directly playable from the browser, with no relay of ours in
 *     the middle. A page served over https may not play an http media
 *     subresource, so an http-only station would have to come back through the
 *     proxy — which is exactly the route this roster was assembled to avoid.
 *     (Radio Swiss Jazz/Pop/Classic were left out for this reason: their https
 *     entry point 302s to an http node, so they cannot be direct-played.)
 *
 * ## The numbers are measured, not marketing
 *
 * Every URL below was probed (status, `audio/*` content type, `icy-br`, and
 * `icy-name` where the host publishes one) and the bitrate recorded in
 * `bitrateKbps` is what the mount actually served. `npm run radio:check` walks
 * the whole dial for the same four things, so a mount that silently drops to a
 * low-bitrate stream — or, worse, starts serving a different station — fails a
 * check instead of reaching a listener.
 *
 * SomaFM is the one list where the top tier is not uniform: their 256 kbps MP3
 * mounts exist per channel, so the channels that have one lead with it and fall
 * back to the 128 kbps AAC mount that every channel carries.
 */

export const AD_FREE_STATIONS: RadioStation[] = [
  /* =============================== SOMAFM =============================== */
  {
    id: "somafm-groove-salad",
    name: "SomaFM Groove Salad",
    country: "United States",
    city: "San Francisco",
    region: "San Francisco",
    genre: "Ambient / Electronic",
    language: "Instrumental",
    frequency: "Digital",
    streamUrl: "https://ice5.somafm.com/groovesalad-256-mp3",
    fallbacks: ["https://ice5.somafm.com/groovesalad-128-aac"],
    bitrateKbps: 256,
    official: true,
    adFree: true,
    color: "#0ea5e9",
    icon: "GS",
    tagline: "A nicely chilled plate of ambient beats and grooves",
    programming: ["Ambient", "Downtempo", "No ads", "Listener-supported"],
    favorite: false,
    verified: true,
  },
  {
    id: "somafm-drone-zone",
    name: "SomaFM Drone Zone",
    country: "United States",
    city: "San Francisco",
    region: "San Francisco",
    genre: "Ambient / Electronic",
    language: "Instrumental",
    frequency: "Digital",
    streamUrl: "https://ice5.somafm.com/dronezone-256-mp3",
    fallbacks: ["https://ice5.somafm.com/dronezone-128-aac"],
    bitrateKbps: 256,
    official: true,
    adFree: true,
    color: "#6366f1",
    icon: "DZ",
    tagline: "Atmospheric ambient space music",
    programming: ["Ambient", "Space music", "No ads", "Listener-supported"],
    favorite: false,
    verified: true,
  },
  {
    id: "somafm-underground-80s",
    name: "SomaFM Underground 80s",
    country: "United States",
    city: "San Francisco",
    region: "San Francisco",
    genre: "Indie / Alternative",
    language: "English",
    frequency: "Digital",
    streamUrl: "https://ice5.somafm.com/u80s-256-mp3",
    fallbacks: ["https://ice5.somafm.com/u80s-128-aac"],
    bitrateKbps: 256,
    official: true,
    adFree: true,
    color: "#a855f7",
    icon: "80",
    tagline: "UK synthpop and a bit of new wave",
    programming: ["Synthpop", "New wave", "No ads", "Listener-supported"],
    favorite: false,
    verified: true,
  },
  {
    id: "somafm-sonic-universe",
    name: "SomaFM Sonic Universe",
    country: "United States",
    city: "San Francisco",
    region: "San Francisco",
    genre: "Jazz",
    language: "Instrumental",
    frequency: "Digital",
    streamUrl: "https://ice5.somafm.com/sonicuniverse-256-mp3",
    fallbacks: ["https://ice5.somafm.com/sonicuniverse-128-aac"],
    bitrateKbps: 256,
    official: true,
    adFree: true,
    color: "#14b8a6",
    icon: "SU",
    tagline: "Nu jazz and avant-garde Euro jazz",
    programming: ["Nu jazz", "Experimental", "No ads", "Listener-supported"],
    favorite: false,
    verified: true,
  },
  {
    id: "somafm-indie-pop",
    name: "SomaFM Indie Pop Rocks",
    country: "United States",
    city: "San Francisco",
    region: "San Francisco",
    genre: "Indie / Alternative",
    language: "English",
    frequency: "Digital",
    streamUrl: "https://ice5.somafm.com/indiepop-128-aac",
    bitrateKbps: 128,
    official: true,
    adFree: true,
    color: "#ec4899",
    icon: "IP",
    tagline: "Indie pop, old and new",
    programming: ["Indie pop", "New releases", "No ads", "Listener-supported"],
    favorite: false,
    verified: true,
  },
  {
    id: "somafm-secret-agent",
    name: "SomaFM Secret Agent",
    country: "United States",
    city: "San Francisco",
    region: "San Francisco",
    genre: "Jazz",
    language: "Instrumental",
    frequency: "Digital",
    streamUrl: "https://ice5.somafm.com/secretagent-128-aac",
    bitrateKbps: 128,
    official: true,
    adFree: true,
    color: "#f59e0b",
    icon: "SA",
    tagline: "The soundtrack for your stylish, mysterious life",
    programming: ["Spy jazz", "Lounge", "No ads", "Listener-supported"],
    favorite: false,
    verified: true,
  },

  /* =========================== RADIO PARADISE =========================== */
  {
    id: "radio-paradise",
    name: "Radio Paradise",
    country: "United States",
    city: "Paradise, CA",
    region: "California",
    genre: "Eclectic",
    language: "English",
    frequency: "Digital",
    streamUrl: "https://stream.radioparadise.com/aac-320",
    bitrateKbps: 320,
    official: true,
    adFree: true,
    color: "#f97316",
    icon: "RP",
    tagline: "Human-curated eclectic rock, at 320 kbps",
    programming: ["Eclectic rock", "Curated by humans", "No ads", "320 kbps"],
    favorite: true,
    verified: true,
  },
  {
    id: "radio-paradise-mellow",
    name: "Radio Paradise — Mellow Mix",
    country: "United States",
    city: "Paradise, CA",
    region: "California",
    genre: "Eclectic",
    language: "English",
    frequency: "Digital",
    streamUrl: "https://stream.radioparadise.com/mellow-320",
    bitrateKbps: 320,
    official: true,
    adFree: true,
    color: "#8b5cf6",
    icon: "RM",
    tagline: "The quieter half of the Paradise library",
    programming: ["Mellow", "Curated by humans", "No ads", "320 kbps"],
    favorite: false,
    verified: true,
  },
  {
    id: "radio-paradise-rock",
    name: "Radio Paradise — Rock Mix",
    country: "United States",
    city: "Paradise, CA",
    region: "California",
    genre: "Eclectic",
    language: "English",
    frequency: "Digital",
    streamUrl: "https://stream.radioparadise.com/rock-320",
    bitrateKbps: 320,
    official: true,
    adFree: true,
    color: "#dc2626",
    icon: "RR",
    tagline: "Guitars, and a lot of them",
    programming: ["Rock", "Curated by humans", "No ads", "320 kbps"],
    favorite: false,
    verified: true,
  },
  {
    id: "radio-paradise-global",
    name: "Radio Paradise — Global Mix",
    country: "United States",
    city: "Paradise, CA",
    region: "California",
    genre: "World",
    language: "English",
    frequency: "Digital",
    streamUrl: "https://stream.radioparadise.com/global-320",
    bitrateKbps: 320,
    official: true,
    adFree: true,
    color: "#eab308",
    icon: "RG",
    tagline: "Global sounds, no ads, 320 kbps",
    programming: ["World music", "Curated by humans", "No ads", "320 kbps"],
    favorite: false,
    verified: true,
  },

  /* ============================ RADIO FRANCE ============================ */
  {
    id: "fip",
    name: "FIP",
    country: "France",
    city: "Paris",
    region: "Paris",
    genre: "Eclectic",
    language: "French / Instrumental",
    frequency: "Digital",
    streamUrl: "https://icecast.radiofrance.fr/fip-hifi.aac",
    bitrateKbps: 192,
    official: true,
    adFree: true,
    color: "#e11d48",
    icon: "FIP",
    tagline: "Jazz, groove, rock and everything in between",
    programming: ["Eclectic", "Public broadcaster", "No ads", "192 kbps"],
    favorite: true,
    verified: true,
  },
  {
    id: "fip-jazz",
    name: "FIP Jazz",
    country: "France",
    city: "Paris",
    region: "Paris",
    genre: "Jazz",
    language: "Instrumental",
    frequency: "Digital",
    streamUrl: "https://icecast.radiofrance.fr/fipjazz-hifi.aac",
    bitrateKbps: 192,
    official: true,
    adFree: true,
    color: "#7c3aed",
    icon: "FJ",
    tagline: "FIP's jazz channel",
    programming: ["Jazz", "Public broadcaster", "No ads", "192 kbps"],
    favorite: false,
    verified: true,
  },
  {
    id: "fip-groove",
    name: "FIP Groove",
    country: "France",
    city: "Paris",
    region: "Paris",
    genre: "Funk / Soul",
    language: "Instrumental",
    frequency: "Digital",
    streamUrl: "https://icecast.radiofrance.fr/fipgroove-hifi.aac",
    bitrateKbps: 192,
    official: true,
    adFree: true,
    color: "#ea580c",
    icon: "FG",
    tagline: "Soul, funk and groove from the FIP family",
    programming: ["Soul", "Funk", "No ads", "192 kbps"],
    favorite: false,
    verified: true,
  },
  {
    id: "fip-world",
    name: "FIP World",
    country: "France",
    city: "Paris",
    region: "Paris",
    genre: "World",
    language: "Multiple",
    frequency: "Digital",
    streamUrl: "https://icecast.radiofrance.fr/fipworld-hifi.aac",
    bitrateKbps: 192,
    official: true,
    adFree: true,
    color: "#059669",
    icon: "FW",
    tagline: "African, Latin and Caribbean music without a single ad",
    programming: ["Afrobeat", "Latin", "No ads", "192 kbps"],
    favorite: false,
    verified: true,
  },
  {
    id: "fip-reggae",
    name: "FIP Reggae",
    country: "France",
    city: "Paris",
    region: "Paris",
    genre: "Reggae",
    language: "English / French",
    frequency: "Digital",
    streamUrl: "https://icecast.radiofrance.fr/fipreggae-hifi.aac",
    bitrateKbps: 192,
    official: true,
    adFree: true,
    color: "#16a34a",
    icon: "FR",
    tagline: "Roots, dub and dancehall",
    programming: ["Roots reggae", "Dub", "No ads", "192 kbps"],
    favorite: false,
    verified: true,
  },

  /* ========================= NTS · KEXP (INDIE) ========================= */
  {
    id: "nts-london",
    name: "NTS Radio",
    country: "United Kingdom",
    city: "London",
    region: "London",
    genre: "Eclectic",
    language: "English",
    frequency: "Digital",
    streamUrl: "https://streams.radiomast.io/nts1",
    bitrateKbps: 256,
    official: true,
    adFree: true,
    color: "#111827",
    icon: "NTS",
    tagline: "London's open-ended radio, 256 kbps",
    programming: ["DJ sets", "Underground", "No ads", "256 kbps"],
    favorite: false,
    verified: true,
  },
  {
    id: "kexp-seattle",
    name: "KEXP",
    country: "United States",
    city: "Seattle",
    region: "Seattle",
    genre: "Indie / Alternative",
    language: "English",
    frequency: "90.3 FM",
    streamUrl: "https://kexp-mp3-128.streamguys1.com/kexp160.aac",
    bitrateKbps: 162,
    official: true,
    adFree: true,
    color: "#0284c7",
    icon: "KX",
    tagline: "Where the music matters — non-commercial, ad-free",
    programming: ["Indie", "Live sessions", "No ads", "Listener-supported"],
    favorite: false,
    verified: true,
  },
];
