export interface RadioStation {
  id: string;
  name: string;
  country: string;
  city: string;
  region: string;
  genre: string;
  language: string;
  frequency: string;
  streamUrl: string;
  /** Ordered backup channels — the player and the probe walk these when the
   *  primary channel fails. Upstream mounts rotate (notably Zeno.fm), so a
   *  station is only as reliable as its fallback chain. */
  fallbacks?: string[];
  color: string;
  icon: string;
  tagline: string;
  logoUrl?: string;
  programming: string[];
  favorite: boolean;
  verified: boolean;
}

/**
 * Every playable channel for a station, primary first. The same-origin proxy
 * (`/api/radio/stream?stationId=&source=`) walks this list server-side, so
 * failover never touches mixed-content or CORS — the browser only ever talks
 * to our origin.
 */
export function stationSources(station: RadioStation): string[] {
  return [station.streamUrl, ...(station.fallbacks ?? [])];
}

export const RADIO_GENRES = [
  "All",
  "Pop / Hits",
  "Urban / R&B",
  "Hip Hop",
  "News / Talk",
  "Vernacular",
  "Indie / Trending",
  "Gospel",
  "Bongo Flava",
  "Afrobeats",
] as const;

export const RADIO_COUNTRIES = [
  "All",
  "Kenya",
  "Uganda",
  "Tanzania",
  "Rwanda",
  "Nigeria",
  "South Africa",
  "Ghana",
  "International",
] as const;

export const STATION_REGIONS = [
  "All",
  "Nairobi",
  "Coast",
  "Rift Valley",
  "Kampala",
  "Dar es Salaam",
  "Arusha",
  "Kigali",
  "Lagos",
  "Johannesburg",
  "Accra",
  "London",
] as const;

export const STATIONS: RadioStation[] = [
  /* ============================== KENYA ============================== */
  {
    id: "capital-fm",
    name: "Capital FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Pop / Hits",
    language: "English",
    frequency: "98.4 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/capitalfm",
    color: "#ef4444",
    icon: "C",
    tagline: "Kenya's #1 hit music station",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Capital_Fm_Logo.svg/200px-Capital_Fm_Logo.svg.png",
    programming: ["Morning Drive", "Hits", "News Bulletins", "Talk"],
    favorite: true,
    verified: true,
  },
  {
    id: "nrg-radio",
    name: "NRG Radio",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Indie / Trending",
    language: "English / Sheng",
    frequency: "90.9 FM",
    streamUrl: "https://streamingv2.shoutcast.com/nrg-radio-ke",
    fallbacks: ["https://stream.zeno.fm/cmgkmed5u18uv"],
    color: "#a855f7",
    icon: "N",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23a855f7'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='16' fill='white' text-anchor='middle'%3ENRG%3C/text%3E%3C/svg%3E",
    tagline: "The future sound of Kenya",
    programming: ["NRG Breakfast", "New Music", "Gen-Z Talk"],
    favorite: true,
    verified: true,
  },
  {
    id: "radio-47",
    name: "Radio 47",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Pop / Hits",
    language: "English / Swahili",
    frequency: "47 FM",
    streamUrl: "https://streaming.shoutcast.com/radio-47?ver=690109",
    fallbacks: ["https://stream.zeno.fm/t65cszbgunhvv"],
    color: "#f59e0b",
    icon: "47",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23f59e0b'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3E47%3C/text%3E%3C/svg%3E",
    tagline: "Songs for every mood",
    programming: ["Classic Mix", "Workday Hits", "Weekend Party"],
    favorite: false,
    verified: true,
  },
  {
    id: "classic-105",
    name: "Classic 105",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Pop / Hits",
    language: "English",
    frequency: "105.3 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/classic105",
    color: "#dc2626",
    icon: "105",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23dc2626'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='16' fill='white' text-anchor='middle'%3E105%3C/text%3E%3C/svg%3E",
    tagline: "Timeless hits from the 80s to today",
    programming: ["Classic Drive", "Greatest Hits", "Workday Anthems"],
    favorite: false,
    verified: true,
  },
  {
    id: "kiss-100",
    name: "Kiss 100",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Urban / R&B",
    language: "English / Sheng",
    frequency: "100.0 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/kiss100fm",
    color: "#f43f5e",
    icon: "K",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23f43f5e'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='24' fill='white' text-anchor='middle'%3EK%3C/text%3E%3C/svg%3E",
    tagline: "Kenya's non-stop urban music",
    programming: ["Kiss Drive", "Urban Hits", "R&B Nights"],
    favorite: false,
    verified: true,
  },
  {
    id: "hot-96",
    name: "Hot 96",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Hip Hop",
    language: "English / Sheng",
    frequency: "96.0 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/hot96",
    color: "#f97316",
    icon: "96",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23f97316'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3E96%3C/text%3E%3C/svg%3E",
    tagline: "Hip hop and urban hits all day",
    programming: ["Hot Breakfast", "Hip Hop Flow", "Night Beats"],
    favorite: false,
    verified: true,
  },
  {
    id: "milele-fm",
    name: "Milele FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Vernacular",
    language: "Swahili",
    frequency: "95.1 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/milelefm",
    color: "#eab308",
    icon: "M",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23eab308'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='24' fill='white' text-anchor='middle'%3EM%3C/text%3E%3C/svg%3E",
    tagline: "Swahili hits, stories and talk",
    programming: ["Bongo Mix", "Swahili Talk", "Request Hour"],
    favorite: false,
    verified: true,
  },
  {
    id: "radio-maisha",
    name: "Radio Maisha",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Vernacular",
    language: "Swahili",
    frequency: "97.1 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/radiomaisha",
    color: "#14b8a6",
    icon: "RM",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%2314b8a6'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3ERM%3C/text%3E%3C/svg%3E",
    tagline: "Swahili music and news from the Nation family",
    programming: ["Maisha Drive", "Swahili News", "Bongo Flava"],
    favorite: false,
    verified: true,
  },
  {
    id: "inooro-fm",
    name: "Inooro FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Vernacular",
    language: "Kikuyu",
    frequency: "98.5 FM",
    streamUrl: "https://atunwadigital.streamguys1.com/inoorofm",
    color: "#16a34a",
    icon: "I",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%2316a34a'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='24' fill='white' text-anchor='middle'%3EI%3C/text%3E%3C/svg%3E",
    tagline: "Kikuyu hits, news and talk",
    programming: ["Kikuyu Mix", "Morning Talk", "Farming Show"],
    favorite: false,
    verified: true,
  },
  {
    id: "nation-fm",
    name: "Nation FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "News / Talk",
    language: "English",
    frequency: "93.3 FM",
    streamUrl: "http://stream.radiojar.com/3by7s8eg65quv",
    color: "#3b82f6",
    icon: "NF",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%233b82f6'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3ENF%3C/text%3E%3C/svg%3E",
    tagline: "Kenya's current affairs voice",
    programming: ["Morning Briefing", "Politics Today", "Business Hour"],
    favorite: false,
    verified: true,
  },
  {
    id: "ghetto-radio",
    name: "Ghetto Radio",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Hip Hop",
    language: "Sheng",
    frequency: "89.5 FM",
    streamUrl: "https://stream.zeno.fm/kvudezx1h2zuv",
    fallbacks: ["https://stream.zeno.fm/cs4q33arb2zuv"],
    color: "#ec4899",
    icon: "G",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23ec4899'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='24' fill='white' text-anchor='middle'%3EG%3C/text%3E%3C/svg%3E",
    tagline: "Sheng hip hop from the streets",
    programming: ["Sheng Flow", "Underground Cyphers", "Gengetone Mix"],
    favorite: false,
    verified: true,
  },
  {
    id: "kameme-fm",
    name: "Kameme FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Vernacular",
    language: "Kikuyu",
    frequency: "101.1 FM",
    streamUrl: "https://kamemefm-atunwadigital.streamguys1.com/kamemefm",
    color: "#22c55e",
    icon: "K",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%2322c55e'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3EKM%3C/text%3E%3C/svg%3E",
    tagline: "Kikuyu hits, news and talk",
    programming: ["Kikuyu Classics", "Community Talk"],
    favorite: false,
    verified: true,
  },

  /* ============================== UGANDA ============================== */
  {
    id: "galaxie-fm",
    name: "Galaxie FM",
    country: "Uganda",
    city: "Kampala",
    region: "Kampala",
    genre: "Pop / Hits",
    language: "English / Luganda",
    frequency: "95.3 FM",
    streamUrl: "https://listen.radioking.com/radio/15684/stream/29075",
    color: "#06b6d4",
    icon: "GX",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%2306b6d4'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3EGX%3C/text%3E%3C/svg%3E",
    tagline: "Kampala's biggest hits",
    programming: ["Breakfast Drive", "Luganda Hits", "Sunday Mix"],
    favorite: true,
    verified: true,
  },
  {
    id: "nrg-uganda",
    name: "NRG Radio Uganda",
    country: "Uganda",
    city: "Kampala",
    region: "Kampala",
    genre: "Indie / Trending",
    language: "English",
    frequency: "91.3 FM",
    streamUrl: "https://dc4.serverse.com/proxy/nrgugstream/stream",
    fallbacks: ["https://stream.zeno.fm/lbca7zintcnuv"],
    color: "#8b5cf6",
    icon: "NU",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%238b5cf6'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3ENU%3C/text%3E%3C/svg%3E",
    tagline: "Uganda's trending sound",
    programming: ["NRG Drive", "Trending Now"],
    favorite: false,
    verified: true,
  },
  {
    id: "spice-fm",
    name: "Spice FM",
    country: "Uganda",
    city: "Kampala",
    region: "Kampala",
    genre: "Urban / R&B",
    language: "English / Luganda",
    frequency: "98.8 FM",
    streamUrl: "https://spice988fm.radioca.st/stream",
    color: "#f43f5e",
    icon: "SP",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23f43f5e'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3ESP%3C/text%3E%3C/svg%3E",
    tagline: "Kampala's urban pulse",
    programming: ["Urban Breakfast", "R&B Evenings", "Luganda Mix"],
    favorite: false,
    verified: true,
  },
  {
    id: "next-radio",
    name: "Next Radio",
    country: "Uganda",
    city: "Kampala",
    region: "Kampala",
    genre: "Pop / Hits",
    language: "English / Luganda",
    frequency: "106.1 FM",
    streamUrl: "https://stream.nextradio.live/listen/nextradio/NextHD",
    fallbacks: [
      "https://stream-154.zeno.fm/lbca7zintcnuv?zs=P9UBEqoSSr69riqZniMYMw",
      "https://stream-154.zeno.fm/lbca7zintcnuv",
    ],
    color: "#eab308",
    icon: "NR",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23eab308'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3ENR%3C/text%3E%3C/svg%3E",
    tagline: "The next big thing",
    programming: ["New Music First", "Kampala Nights"],
    favorite: false,
    verified: true,
  },
  {
    id: "sanyu-fm",
    name: "Sanyu FM",
    country: "Uganda",
    city: "Kampala",
    region: "Kampala",
    genre: "Pop / Hits",
    language: "English / Luganda",
    frequency: "88.2 FM",
    streamUrl: "https://s44.myradiostream.com:8138/stream",
    fallbacks: ["http://s44.myradiostream.com:8138/stream"],
    color: "#f97316",
    icon: "S",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23f97316'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='24' fill='white' text-anchor='middle'%3ES%3C/text%3E%3C/svg%3E",
    tagline: "Uganda's oldest private station",
    programming: ["Morning Breeze", "Luganda Hits", "Classic Show"],
    favorite: false,
    verified: true,
  },

  /* ============================= TANZANIA ============================= */
  {
    id: "ear-radio",
    name: "East Africa Radio",
    country: "Tanzania",
    city: "Dar es Salaam",
    region: "Dar es Salaam",
    genre: "Urban / R&B",
    language: "Swahili / English",
    frequency: "Digital",
    streamUrl: "https://eatv.radioca.st/stream",
    color: "#10b981",
    icon: "EA",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%2310b981'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3EEA%3C/text%3E%3C/svg%3E",
    tagline: "Bongo flava and East African vibes",
    programming: ["Bongo Flava Mix", "East African Hits", "Request Show"],
    favorite: true,
    verified: true,
  },
  {
    id: "capital-tz",
    name: "Capital Radio",
    country: "Tanzania",
    city: "Dar es Salaam",
    region: "Dar es Salaam",
    genre: "Pop / Hits",
    language: "Swahili / English",
    frequency: "94.1 FM",
    streamUrl: "https://capitalradio.radioca.st/stream",
    color: "#0ea5e9",
    icon: "CT",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%230ea5e9'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3ECT%3C/text%3E%3C/svg%3E",
    tagline: "Tanzania's hit station",
    programming: ["Capital Drive", "Bongo Hits", "Weekend Mix"],
    favorite: false,
    verified: true,
  },
  {
    id: "crown-fm",
    name: "Crown FM",
    country: "Tanzania",
    city: "Arusha",
    region: "Arusha",
    genre: "Vernacular",
    language: "Swahili",
    frequency: "103.4 FM",
    streamUrl: "https://radio.crownmedia.co.tz:8443/crown",
    color: "#84cc16",
    icon: "CR",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%2384cc16'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3ECR%3C/text%3E%3C/svg%3E",
    tagline: "Northern Tanzania's voice",
    programming: ["Arusha Morning", "Swahili Classics", "Maasai Stories"],
    favorite: false,
    verified: true,
  },
  {
    id: "clouds-fm",
    name: "Clouds FM",
    country: "Tanzania",
    city: "Dar es Salaam",
    region: "Dar es Salaam",
    genre: "Bongo Flava",
    language: "Swahili",
    frequency: "102.5 FM",
    streamUrl: "http://eu6.fastcast4u.com:5306/;",
    color: "#8b5cf6",
    icon: "CF",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%238b5cf6'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3ECF%3C/text%3E%3C/svg%3E",
    tagline: "Tanzania's #1 Bongo Flava station",
    programming: ["Clouds Breakfast", "Bongo Hot", "Mic Tamtam"],
    favorite: false,
    verified: true,
  },

  /* ============================== RWANDA ============================== */
  {
    id: "radio-rwanda",
    name: "Radio Rwanda",
    country: "Rwanda",
    city: "Kigali",
    region: "Kigali",
    genre: "News / Talk",
    language: "Kinyarwanda / French",
    frequency: "95.0 FM",
    streamUrl: "https://listen.rba.co.rw:8008/rwanda/",
    fallbacks: ["http://stream.zeno.fm/eequgfw72hhvv"],
    color: "#2563eb",
    icon: "RR",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%232563eb'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3ERR%3C/text%3E%3C/svg%3E",
    tagline: "The national broadcaster",
    programming: ["Morning News", "Kinyarwanda Talk", "National Service"],
    favorite: false,
    verified: true,
  },
  {
    id: "magic-fm",
    name: "Magic FM 90.7",
    country: "Rwanda",
    city: "Kigali",
    region: "Kigali",
    genre: "Pop / Hits",
    language: "Kinyarwanda / English",
    frequency: "90.7 FM",
    streamUrl: "http://listen.rba.co.rw:8080/",
    fallbacks: ["http://listen.rba.co.rw:8080/;"],
    color: "#db2777",
    icon: "M",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23db2777'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='24' fill='white' text-anchor='middle'%3EM%3C/text%3E%3C/svg%3E",
    tagline: "Kigali's Feel-Good hits — RBA",
    programming: ["Morning Magic", "Kinyarwanda Hits", "Weekend Party"],
    favorite: false,
    verified: true,
  },

  /* ============================== NIGERIA ============================== */
  {
    id: "beat-fm",
    name: "Afrobeats Gospel Radio",
    country: "Nigeria",
    city: "Lagos",
    region: "Lagos",
    genre: "Afrobeats",
    language: "English / Pidgin",
    frequency: "Digital",
    streamUrl: "https://stream.zeno.fm/zyd9stmdlnlvv",
    color: "#f59e0b",
    icon: "BF",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23f59e0b'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3EBF%3C/text%3E%3C/svg%3E",
    tagline: "Afrobeats hits with a soulful twist",
    programming: ["Afrobeats Mix", "Gospel Grooves", "Lagos Nights"],
    favorite: false,
    verified: true,
  },
  {
    id: "cool-fm",
    name: "Cool FM 96.9",
    country: "Nigeria",
    city: "Lagos",
    region: "Lagos",
    genre: "Pop / Hits",
    language: "English / Pidgin",
    frequency: "96.9 FM",
    streamUrl: "http://18063.live.streamtheworld.com:3690/CJMKFMAAC_SC",
    color: "#06b6d4",
    icon: "CF",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%2306b6d4'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3ECF%3C/text%3E%3C/svg%3E",
    tagline: "Lagos' hottest hits",
    programming: ["Cool Drive", "Hit Music", "Lagos Vibes"],
    favorite: false,
    verified: true,
  },
  {
    id: "wazobia-fm",
    name: "Wazobia FM 99.5",
    country: "Nigeria",
    city: "Lagos",
    region: "Lagos",
    genre: "Vernacular",
    language: "Yoruba / Pidgin",
    frequency: "99.5 FM",
    streamUrl: "https://wazobiafmlagos951-atunwadigital.streamguys1.com/wazobiafmlagos951",
    color: "#16a34a",
    icon: "W",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%2316a34a'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='24' fill='white' text-anchor='middle'%3EW%3C/text%3E%3C/svg%3E",
    tagline: "Lagos in your language",
    programming: ["Yoruba Morning", "Pidgin Show", "Local Hits"],
    favorite: false,
    verified: true,
  },

  /* ============================= SOUTH AFRICA ============================ */
  {
    id: "metro-fm",
    name: "METRO FM",
    country: "South Africa",
    city: "Johannesburg",
    region: "Johannesburg",
    genre: "Urban / R&B",
    language: "English / Zulu",
    frequency: "104.8 FM",
    streamUrl: "http://28503.live.streamtheworld.com:3690/METRO_FMAAC_SC",
    color: "#dc2626",
    icon: "M",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23dc2626'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3EMF%3C/text%3E%3C/svg%3E",
    tagline: "South Africa's urban beat",
    programming: ["Metro Drive", "Urban Jazz", "House Music"],
    favorite: false,
    verified: true,
  },
  {
    id: "5fm",
    name: "5FM",
    country: "South Africa",
    city: "Johannesburg",
    region: "Johannesburg",
    genre: "Pop / Hits",
    language: "English",
    frequency: "95.0 FM",
    streamUrl: "https://cdn.cybercdn.live/Darom_1015FM/Live/icecast.audio",
    color: "#f97316",
    icon: "5",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23f97316'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='24' fill='white' text-anchor='middle'%3E5%3C/text%3E%3C/svg%3E",
    tagline: "South Africa's youth radio",
    programming: ["5 Breakfast", "Top 40", "After Dark"],
    favorite: false,
    verified: true,
  },
  {
    id: "jacaranda-fm",
    name: "Jacaranda FM",
    country: "South Africa",
    city: "Johannesburg",
    region: "Johannesburg",
    genre: "Pop / Hits",
    language: "English / Afrikaans",
    frequency: "94.2 FM",
    streamUrl: "https://live.jacarandafm.com/jacarandahigh.mp3",
    color: "#7c3aed",
    icon: "JF",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%237c3aed'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3EJF%3C/text%3E%3C/svg%3E",
    tagline: "Great music and more",
    programming: ["Martin Bester", "Top 40", "Weekend Breakfast"],
    favorite: false,
    verified: true,
  },

  /* ================================ GHANA ================================ */
  {
    id: "joy-fm",
    name: "Joy FM",
    country: "Ghana",
    city: "Accra",
    region: "Accra",
    genre: "News / Talk",
    language: "English / Twi",
    frequency: "99.7 FM",
    streamUrl: "https://gateway.cdnstream1.com/2808_96.aac",
    color: "#2563eb",
    icon: "JF",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%232563eb'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3EJF%3C/text%3E%3C/svg%3E",
    tagline: "Ghana's most trusted news station",
    programming: ["Super Morning Show", "Newsfile", "Prime Take"],
    favorite: false,
    verified: true,
  },
  {
    id: "adom-fm",
    name: "Adom FM",
    country: "Ghana",
    city: "Accra",
    region: "Accra",
    genre: "Vernacular",
    language: "Twi",
    frequency: "106.3 FM",
    streamUrl: "https://mmg.streamguys1.com/AdomFM-mp3",
    color: "#ef4444",
    icon: "AF",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23ef4444'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='18' fill='white' text-anchor='middle'%3EAF%3C/text%3E%3C/svg%3E",
    tagline: "Ghana's leading Twi station",
    programming: ["Adom Dwaso", "Badwam Tribunal", "Nkommo Womu"],
    favorite: false,
    verified: true,
  },

  /* ============================ INTERNATIONAL =========================== */
  {
    id: "bbc-world",
    name: "BBC World Service",
    country: "International",
    city: "London",
    region: "London",
    genre: "News / Talk",
    language: "English",
    frequency: "Digital",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service",
    color: "#991b1b",
    icon: "BBC",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23991b1b'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='16' fill='white' text-anchor='middle'%3EBBC%3C/text%3E%3C/svg%3E",
    tagline: "The world's radio station",
    programming: ["World News", "Africa Daily", "Focus on Africa"],
    favorite: false,
    verified: true,
  },
  {
    id: "bbc-east-africa",
    name: "BBC World Service — East Africa",
    country: "International",
    city: "London",
    region: "London",
    genre: "News / Talk",
    language: "English",
    frequency: "Digital",
    streamUrl: "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service_east_asia",
    color: "#2563eb",
    icon: "F24",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%232563eb'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='16' fill='white' text-anchor='middle'%3EF24%3C/text%3E%3C/svg%3E",
    tagline: "BBC's East Africa news feed",
    programming: ["World News", "Africa Daily", "Focus on Africa"],
    favorite: false,
    verified: true,
  },
  {
    id: "kbc-english",
    name: "KBC English Service",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "News / Talk",
    language: "English / Swahili",
    frequency: "Digital",
    streamUrl: "http://stream.zeno.fm/ud2u96xst5quv",
    fallbacks: ["https://stream.zeno.fm/ud2u96xst5quv"],
    color: "#06b6d4",
    icon: "NTV",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%2306b6d4'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='16' fill='white' text-anchor='middle'%3ENTV%3C/text%3E%3C/svg%3E",
    tagline: "The national broadcaster, live",
    programming: ["National News", "Swahili Service", "English Service"],
    favorite: false,
    verified: true,
  },
  {
    id: "qfm",
    name: "Q FM",
    country: "Kenya",
    city: "Nairobi",
    region: "Nairobi",
    genre: "Urban / R&B",
    language: "English / Sheng",
    frequency: "96.3 FM",
    streamUrl: "https://edge.mixlr.com/channel/rumps",
    fallbacks: ["http://edge.mixlr.com/channel/rumps"],
    color: "#e879f9",
    icon: "Q",
    logoUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23e879f9'/%3E%3Ctext x='32' y='42' font-family='Arial' font-weight='bold' font-size='24' fill='white' text-anchor='middle'%3EQ%3C/text%3E%3C/svg%3E",
    tagline: "Nairobi's R&B groove",
    programming: ["R&B Evenings", "Sheng Hour", "Weekend Mix"],
    favorite: false,
    verified: true,
  },
];

export function getStationById(id: string | null): RadioStation | null {
  if (!id) return null;
  return STATIONS.find((s) => s.id === id) ?? null;
}

export function getStationsByCountry(country: string): RadioStation[] {
  return STATIONS.filter((s) => s.country === country);
}
