"use client";

import { cn } from "@/lib/utils";

/**
 * The connectPlus mark — the official savanna-sunset emblem.
 *
 * This replaced an inline SVG approximation of the same idea when the real
 * artwork arrived. It is a raster now, which is a deliberate trade: the supplied
 * illustration is a layered, shaded scene (sunset disc, lion, acacia, birds) that
 * no hand-written path reproduces faithfully.
 *
 * The reason one file is enough for both themes is geometry: the artwork's disc
 * is opaque and circular, so it reads identically on the light canvas and on
 * charcoal. There is no `dark:` variant to keep in sync, and no second asset to
 * forget — which is exactly how a logo ends up stale on one theme.
 *
 * The two supplied plate lockups (white plate with a dark wordmark, dark plate
 * with a cream one) are used where a *stacked* logo has room — see
 * public/brand/lockup-*.png, regenerated by scripts/generate-brand.mjs.
 */
export default function ConnectPlusMark({
  className,
  label = "connectPlus",
}: {
  className?: string;
  /** Accessible name. Pass "" when the mark sits beside the visible wordmark. */
  label?: string;
}) {
  return (
    /* eslint-disable-next-line @next/next/no-img-element -- a 69kB fixed asset
       drawn at 32-44px, already pre-cached by the service worker. Routing it
       through the image optimizer would add a round trip and a cache entry for
       no bytes saved. */
    <img
      src="/brand/mark.png"
      alt={label}
      aria-hidden={label ? undefined : true}
      width={256}
      height={256}
      decoding="async"
      className={cn("block h-full w-full object-contain", className)}
    />
  );
}
