// Savanna roundel mark — savanna sun + acacia silhouette on amber→terracotta.
// Mirrors the design generated by scripts/generate-assets.mjs for brand consistency.
"use client";

import { useId } from "react";
import { cn } from "@/lib/utils";

export default function SavannaMark({ className }: { className?: string }) {
  const rawId = useId();
  const id = `sav-${rawId.replace(/[^a-zA-Z0-9]/g, "")}`;
  return (
    <svg
      viewBox="0 0 100 100"
      className={cn("block", className)}
      role="img"
      aria-label="connectPlus savanna mark"
    >
      <defs>
        <linearGradient id={id} x1="0" y1="0" x2="100" y2="100">
          <stop offset="0" stopColor="#fbbc24" />
          <stop offset="100%" stopColor="#9a3412" />
        </linearGradient>
      </defs>
      <circle cx="50" cy="50" r="50" fill={`url(#${id})`} />

      {/* Pale gold sunset sun (upper left) */}
      <circle cx="30.7" cy="27.9" r="20.2" fill="#fde68a" opacity="0.95" />
      {/* "+" cut on the sun */}
      <ellipse cx="33.5" cy="30.6" rx="7.4" ry="3.2" fill="#eec955" opacity="0.9" />
      <ellipse cx="33.5" cy="30.6" rx="3.2" ry="7.4" fill="#eec955" opacity="0.9" />

      {/* Acacia canopy (charcoal, lower right) */}
      <ellipse cx="57.4" cy="65.6" rx="13.8" ry="6.4" fill="#1a1716" opacity="0.92" />
      <ellipse cx="49.4" cy="73.9" rx="11.3" ry="5.9" fill="#1b1818" opacity="0.96" />
      <ellipse cx="65.4" cy="73.9" rx="11.3" ry="5.9" fill="#1c1917" />
      {/* Trunk */}
      <ellipse cx="57.4" cy="81.3" rx="1.4" ry="13.8" fill="#1c1917" opacity="0.95" />
      {/* Ground shadow */}
      <ellipse cx="57.4" cy="96.9" rx="19.3" ry="2.3" fill="#000000" opacity="0.28" />
    </svg>
  );
}